### ISSUE TITLE
Authenticate with EPIC Hyperspace using SMART flow

### ISSUE THREAD

**Issue by pmanko** [uwcirg/cpro-common#5]
- [x] Hyperspace Button
- [x] MyChart Button
- [x] Provide redirect for Hyperspace
- [x] Provide redirect for MyChart
- [ ] Handle direct launch
- [x] Handle app-context launch
- [x] Request required user data
